"""
predict.py — Run the trained detector on new text
==================================================
Usage:
  Interactive mode (default):
      python predict.py

  Single text via argument:
      python predict.py "Paste your text here between quotes."

  From a .txt file:
      python predict.py --file path/to/essay.txt
"""

import os
import sys
import pickle
import argparse
import numpy as np
from features import extract_features, FEATURE_NAMES


MODEL_PATH = "model/detector.pkl"


def load_model():
    if not os.path.exists(MODEL_PATH):
        print(f"\nERROR: Model not found at '{MODEL_PATH}'.")
        print("  Run  python train.py  first to train the model.")
        sys.exit(1)
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)


def predict(clf, text: str) -> dict:
    """Return prediction dict with label, confidence, and top features."""
    feats = np.array(extract_features(text)).reshape(1, -1)
    label_idx   = clf.predict(feats)[0]
    proba       = clf.predict_proba(feats)[0]
    confidence  = proba[label_idx] * 100

    label = "🤖 AI-Generated" if label_idx == 1 else "🧑 Human-Written"

    # feature importances (only available for tree-based models)
    importances = getattr(clf, "feature_importances_", None)
    top_features = []
    if importances is not None:
        feat_vals = extract_features(text)
        ranked = sorted(
            zip(FEATURE_NAMES, importances, feat_vals),
            key=lambda x: x[1], reverse=True
        )[:5]
        top_features = [(name, f"{imp:.3f}", f"{val:.4f}") for name, imp, val in ranked]

    return {
        "label":        label,
        "label_idx":    label_idx,
        "confidence":   confidence,
        "prob_human":   proba[0] * 100,
        "prob_ai":      proba[1] * 100,
        "top_features": top_features,
    }


def print_result(result: dict):
    print("\n" + "═" * 52)
    print(f"  Prediction  : {result['label']}")
    print(f"  Confidence  : {result['confidence']:.1f}%")
    print(f"  P(Human)    : {result['prob_human']:.1f}%")
    print(f"  P(AI)       : {result['prob_ai']:.1f}%")
    if result["top_features"]:
        print("\n  Top contributing features:")
        print(f"  {'Feature':<25} {'Importance':>10}  {'Your value':>10}")
        print("  " + "-" * 48)
        for name, imp, val in result["top_features"]:
            print(f"  {name:<25} {imp:>10}  {val:>10}")
    print("═" * 52 + "\n")


def interactive_mode(clf):
    print("\n╔══════════════════════════════════════╗")
    print("║   AI vs Human Text Detector  v1.0   ║")
    print("╚══════════════════════════════════════╝")
    print("  Paste or type text, then press Enter twice.")
    print("  Type  'quit'  or  'exit'  to stop.\n")

    while True:
        lines = []
        print("─" * 52)
        try:
            while True:
                line = input()
                if line.lower() in ("quit", "exit"):
                    print("\nGoodbye!\n")
                    return
                if line == "" and lines and lines[-1] == "":
                    break
                lines.append(line)
        except EOFError:
            break

        text = "\n".join(lines).strip()
        if not text:
            print("  (no text entered, try again)")
            continue

        if len(text.split()) < 10:
            print("  ⚠  Text is very short — results may be unreliable (aim for 50+ words).")

        result = predict(clf, text)
        print_result(result)


def main():
    parser = argparse.ArgumentParser(
        description="Detect whether text was written by a human or generated by AI."
    )
    parser.add_argument(
        "text", nargs="?", default=None,
        help="Text string to classify (optional; uses interactive mode if omitted)."
    )
    parser.add_argument(
        "--file", "-f", default=None,
        help="Path to a .txt file to classify."
    )
    args = parser.parse_args()

    clf = load_model()

    if args.file:
        if not os.path.exists(args.file):
            print(f"ERROR: File not found: {args.file}")
            sys.exit(1)
        with open(args.file, "r", encoding="utf-8") as fh:
            text = fh.read()
        print(f"\nAnalysing file: {args.file}")
        result = predict(clf, text)
        print_result(result)

    elif args.text:
        result = predict(clf, args.text)
        print_result(result)

    else:
        interactive_mode(clf)


if __name__ == "__main__":
    main()
